proxy:
    port: 8080
backends:
    - name: web-servers
      servers:
        - url: http://localhost:3001
          weight: 3
          active: true
          max_connections: 100
          health_check_endpoint: /health
        - url: http://localhost:3002
          weight: 2
          active: true
          max_connections: 100
          health_check_endpoint: /health
        - url: http://localhost:3003
          weight: 4
          active: true
          max_connections: 100
          health_check_endpoint: /status
      health_check: /health
      balance_mode: adaptive_weighted
      health_interval: 30s
      timeout: 10s
      retries: 2
      circuit_breaker:
        failure_threshold: 3
        recovery_timeout: 1m0s
        enabled: true
      min_servers: 1
      max_servers: 3
triggers:
    smart:
        enabled: true
        evaluation_interval: 30s
        short_window: 5m0s
        long_window: 30m0s
        cooldown: 1m0s
        stability_threshold: 0.5
        scale_up_score: 0.12
        scale_down_score: 0.1
        long_avg_scale_up_min: 0
        long_avg_scale_down_max: 1
        trend_threshold: 0.01
    traffic:
        high_threshold: 50
        low_threshold: 5
        high_action: scale_up
        low_action: scale_down
    schedule: []
actions:
    evening_scale:
        url: http://localhost:8082/actions/evening_scale
        method: POST
    morning_scale:
        url: http://localhost:8082/actions/morning_scale
        method: POST
    scale_down:
        url: http://localhost:8082/actions/scale_down
        method: POST
    scale_up:
        url: http://localhost:8082/actions/scale_up
        method: POST
security:
    api_keys:
        - "your-api-key-here"
        - "backup-api-key-here"
    admin_api_keys:
        - "your-admin-key-here"