version: '3.8'

services:
  go-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-proxy
    ports:
      - "8080:8080"  # Proxy port
      - "8081:8081"  # Metrics port
      - "8082:8082"  # Config API port
    volumes:
      - ./config.yaml:/app/config.yaml:ro  # Mount config as read-only
    environment:
      - GO_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy-network

  # Example backend services for testing
  backend1:
    image: nginx:alpine
    container_name: backend1
    ports:
      - "3001:80"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-network

  backend2:
    image: nginx:alpine
    container_name: backend2
    ports:
      - "3002:80"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge