name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build and push binary
      env:
        GH_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
      run: |
        VERSION=$(date +"%Y%m%d.%H%M")
        
        go mod download
        CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags="-s -w" -trimpath -o go-proxy-${VERSION} ./cmd
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git clone https://x-access-token:${GH_TOKEN}@github.com/flitware-oss/go-proxy-releases.git
        cd go-proxy-releases

        cp ../go-proxy-${VERSION} .
        
        git add go-proxy-${VERSION}
        git commit -m "Add go-proxy v${VERSION}"
        git push